// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";

// Note: Not using new prisma config format as it's not compatible with v5
export default {};

